name: Build

on:
  push:
    branches: master
    tags: '**'
  pull_request:

env:
  DOTNET_SKIP_FIRST_TIME_EXPERIENCE: true
  DOTNET_CLI_TELEMETRY_OPTOUT: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v1
    - name: Setup .NET Core
      uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Build
      run: dotnet build src/NeardSharp.sln --configuration Release 
    - name: Test
      run: dotnet test src/NeardSharp.sln --no-build --configuration Release
  pack:
    runs-on: ubuntu-latest
    needs: build
    if: github.event_name == 'push'
    steps:
    - uses: actions/checkout@v1
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - name: Pack
      run: dotnet pack src/NeardSharp.sln --output ./artifacts --configuration Release
    - uses: actions/upload-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
  publish:
    runs-on: ubuntu-latest
    needs: pack
    if: github.event_name == 'push'
    steps:
    - uses: actions/download-artifact@v1
      with:
        name: artifacts
        path: ./artifacts
    - uses: actions/setup-dotnet@v1
      with:
        dotnet-version: 3.1.102
    - run: cd ./artifacts/
    - name: Publish packages
      run: dotnet nuget push **.nupkg --skip-duplicate -s https://api.nuget.org/v3/index.json -k ${{ secrets.NUGET_TOKEN }}
